### ISSUE TITLE
Duplicate clip missing?

### ISSUE THREAD

**Issue by hemisphera** [ideoforms/AbletonOSC#100]
I am missing an endpoint that lets me duplicate a clip. I have seen the `/live/song/duplicate_scene` and `/live/clip/duplicate_loop`, but that's not what I am looking for. Is there even a Live API call available for this?

I would love to give a hand in implementing this, but I am having trouble with the documentation for the API Live exposes. What documentation do you use as reference? All that I have found on the web is either outdated incomplete. For example: I cannot find documentation for the `schedule_message` method you are using anywhere.

**Comment by ideoforms** [comment]
Thanks for the query. There is a `duplicate_clip_to` method for this; I've added the functionality in the [latest commit](https://github.com/ideoforms/AbletonOSC/commit/978134aed4d13bcd252f39e9d46b520d31aceca5), so closing this issue. Let me know how you get on!

For future reference, the Live API documentatation has been reverse-engineered in a couple of places:
 - [Per-class APIs (structure-void.com)](https://structure-void.com/PythonLiveAPI_documentation/Live11.0.xml)
 - [Internal APIs for control elements](https://github.com/gluon/AbletonLive11_MIDIRemoteScripts/blob/main/ableton/v2/control_surface/control_surface.py), which is where `schedule_message` resides
