### ISSUE TITLE
/api/reload messes up listeners

### ISSUE THREAD

**Issue by Coupe70** [ideoforms/AbletonOSC#104]
Maybe I'm using this wrong, so maybe it's not critical.
Maybe what happens is even logical.

I assumed that using /api/reload would be the same as de- and reselecting AbletonOSC as
Ableton control surface to reset "everything". But it seems this does not work.

a) `/live/clip_slot/start_listen/has_clip, 0, 0`
b) returns the expected messages when creating / deleting a clip in slot 0,0
c) `/live/clip_slot/stop_listen/has_clip, 0, 0`
d) stops to return the messages as expected
OK.

a) `/live/clip_slot/start_listen/has_clip, 0, 0`
b) returns the expected messages when creating / deleting a clip in slot 0,0
c) `/live/api/reload`
d) listener keeps being active, returning the usual messages
e) `/live/clip_slot/stop_listen/has_clip, 0, 0`
f) does not work, messages keep coming - seems like AbletonOSC has forgotten about listener, but it's still there in Live
g) `/live/clip_slot/start_listen/has_clip, 0, 0`
h) messages are returned TWICE
i) every `/api/reload` + `/start_listen/has_clip, 0, 0` adds another listener instance resulting in 3, 4, 5, 6 returned messages
j) can only be resetted by de- and reselecting AbletonOSC as Ableton control surface

As I said, probably kind of logical when you only reset AbletonOSC itself, but not reset the "script-connection" in Live.
But maybe something can be done to make Live reset the script or make AbletonOSC kill all listeners on /reload...?

**Comment by ideoforms** [comment]
Oh yes, just taken a look and I can see this happening in the logs. The handlers and listeners _are_ supposed to be killed on `/live/api/reload`, but I found and hopefully fixed a bug that caused this not to happen properly. Can you test now?

**Comment by Coupe70** [comment]
No, that does not work, still behaves as described.
I can only use `/stop_listen/has_clip` to remove ONE of the has_clip-listeners (e.g. from 4 to 3), propbably the last one added, the others are stuck.

**Comment by ideoforms** [comment]
Try now?

**Comment by Coupe70** [comment]
First `/reload` gives
**STRING(Error handling OSC message: Python argument types in Clip.remove_name_listener(Clip, function)
did not match C++ signature:
remove_name_listener(class TPyHandle<class AClip>, class boost::python::api::object))**
After that `/start_listen/name` and `/reload return`
**Unknown OSC address**

**Comment by ideoforms** [comment]
Ah yes, this still wasn't working as expected in the following case:
 - add a clip and add a name listener to the clip
 - remove the clip and re-add a clip in the same slot
 - reload the API
This would cause an error when the API was being setup, which would cause all the other callbacks to fail 🙃

I've now fixed that case too... let me know..!

**Comment by Coupe70** [comment]
![grafik](https://github.com/ideoforms/AbletonOSC/assets/70244400/fced945c-467b-4230-aa2e-38403bceb1a5)
