### ISSUE TITLE
Live 12 support

### ISSUE THREAD

**Issue by esaruoho** [ideoforms/AbletonOSC#117]
Hi, is Live 12 support incoming for AbletonOSC?

**Comment by ideoforms** [comment]
I don't currently have access to the Live 12 beta, but will get a copy when it's released and be able to confirm then.

If you have access to the beta and can verify, any reports would be appreciated!

**Comment by esaruoho** [comment]
I do have access but am on a new computer so dont yet ha e AbletonOSC installed. I will check and see if it works!! Fingers crossed :)

**Comment by esaruoho** [comment]
<img width="1016" alt="Screenshot 2024-02-23 at 23 08 01" src="https://github.com/ideoforms/AbletonOSC/assets/4966687/6732a0b6-d700-4381-b755-201f3e0351e6">

i'll try and send messages to it hopefully tomorrow evening. is this promising, however, @ideoforms ?

**Comment by ideoforms** [comment]
Thanks for the report @esaruoho !

**Comment by esaruoho** [comment]
yep, TouchOSC people fixed the Grid object issues.

i'm now trying to figure out how to get my TouchOSC script to talk to Ableton Live 12 again. I definitely had them working on February, but it's September now. Trying to remember where all of this was. 

what i can say is that i'm on macOS Sonoma 14.6.1 

I've tried with Ableton Live 11 and Ableton Live 12, i've re-installed and copied and installed, and both state that the old folder is able to be recognized and they connect to 11000, but for some reason, i can't make the connection.

to add insult to injury, even sending messages from `./run-console.py` no longer work.

Is there some form of getting more details from ./run-console.py ? @ideoforms  like more logging?


this is definitely the computer i was using back then, which is very strange. i might've updated to a newer version of Python and a newer version of macOS, but i'm completely in the dark here, being unable to get ./run

**Comment by ideoforms** [comment]
Hmm, that's strange. Try running `./run-console.py -v`  — this turns on verbose output, which will report whenever a message is received from Ableton. 

I've just tested here with the latest Live 12 on macOS Ventura and it is behaving as expected. Here's the output I get if I try querying the tempo:

```
(1823)(master)(mbp2022:AbletonOSC)$ ./run-console.py
AbletonOSC command console
Usage: /live/osc/command [params]
>>> /live/song/get/tempo
120.0
>>> ^D
(1823)(master)(mbp2022:AbletonOSC)$ ./run-console.py  -v
AbletonOSC command console
Usage: /live/osc/command [params]
>>> /live/startup ()
/live/application/get/average_process_usage ()
/live/song/get/tempo
/live/song/get/tempo (120.0,)
120.0
>>> ^D
```

Can you confirm that: AbletonOSC is visible in the Control Surface column in "Link, Tempo & MIDI" (in Preferences)?
You should also see some logging in the internal AbletonOSC logs: `~/Music/Ableton/User Library/Remote Scripts/AbletonOSC/logs/abletonosc.log`

**Comment by esaruoho** [comment]
this is what i get, unfortunately:

```
$ ./run-console.py -v 
AbletonOSC command console
Usage: /live/osc/command [params]
>>> /live/osc/get/tempo
>>> /live/osc/get/tempo
>>> /live/osc/get/tempo
>>> /live/startup ()
(after which i pressed ctrl-c)
>>> Traceback (most recent call last):
  File "/Users/esaruoho/work/AbletonOSC/./run-console.py", line 96, in <module>
    main(args)
  File "/Users/esaruoho/work/AbletonOSC/./run-console.py", line 52, in main
    command_str = input(">>> ")
                  ^^^^^^^^^^^^^
KeyboardInterrupt
```
<img width="442" alt="Screenshot 2024-09-18 at 22 32 46" src="https://github.com/user-attachments/assets/2e204043-75c7-4e99-a131-49cda5314ecd">

i tried it without sync,remote,mpe. no change. 

when i turn the row the AbletonOSC is on, to Off, and re-select it, i do get the yellow message at the bottom:

<img width="1042" alt="Screenshot 2024-09-18 at 22 33 34" src="https://github.com/user-attachments/assets/0901f0e4-f4f4-47eb-a2a6-6157df72a132">

there's a brief delay between `/live/osc/get/tempo` and the next `>>>` 
but nothing more.
not sure how to proceed.

**Comment by esaruoho** [comment]
ok, three more details.
```
$ ./run-console.py -v
/Users/esaruoho/Music/Ableton/User Library/Remote Scripts/AbletonOSC/pythonosc/dispatcher.py:153: SyntaxWarning: invalid escape sequence '\w'
  pattern = pattern.replace('\\*', '[\w|\+]*')
AbletonOSC command console
Usage: /live/osc/command [params]
>>> 
```

this strange error.

also, i am using an older AbletonOSC build. the reason for that?
i downloaded the current zip, and followed the advice for  unzipping, and renaming the folder abletonosc-master to AbletonOSC.
i put that folder into the User Scripts, and while it shows in the settings menu, it does not give me the yellow message at the bottom, which is very strange, right?

**Comment by ideoforms** [comment]
To debug the startup issue with the latest .zip, could you try running Live with the latest AbletonOSC installed/enabled, run the instructions in ["Debugging compile-time issues"](https://github.com/ideoforms/AbletonOSC/blob/master/CONTRIBUTING.md#debugging-compile-time-issues) and paste the output?
And do the same with the older version installed in case it's hitting some runtime error.

I am also running Live 12.0.25 and no problems. I wonder if it's a network issue.

Could you also paste the output of the below terminal command which will list UDP ports that Live is listening on?
```
sudo lsof -nP -i4UDP | grep ^Live
```

**Comment by esaruoho** [comment]
ok. this is very strange.  i was getting no results, until i thought, let's close TouchOSC.

now that i completely quit TouchOSC - but have TouchOSC Bridge running, now i get messages!

i'm starting to think i maybe had TouchOSC listening to 11000 and capturing it, and that's why the errors. i'll continue troubleshooting from this point of view. Thanks a lot for your help!

```
>>> /live/song/get/tempo
/live/song/get/tempo (86.75,)
(86.75,)
>>> 
```

**Comment by ideoforms** [comment]
Thanks @esaruoho, those errors just indicate that AbletonOSC can't be reached.

If you run `sudo lsof -nP -i4UDP | grep 11000`, that will tell you if anything else is listening on that port (the process name being in the first column), which would definitely produce the symptoms you've described.

I've also added an error message to the latest commit of AbletonOSC that will indicate whether it encounters a problem binding to the network port.

**Comment by esaruoho** [comment]
thanks for adding the error message!

upon checking, i had both running:
```
$ sudo lsof -nP -i4UDP | grep 11000
Password:
Live      16844       esaruoho  179u  IPv4 0x634db4a0a3942f99      0t0  UDP *:11000
TouchOSC  25783       esaruoho    7u  IPv6 0x6d2de584fb3ca3e9      0t0  UDP *:11000
```

so i closed TouchOSC and only ran Live, and i still got 22 failed and 32 passed.


here's a video of various trials of it. 
https://www.loom.com/share/910732a274cd470dacfe82df82f74977?sid=458d2b3a-d67d-4915-bb9c-a890562697df

what i noticed, is, that if i have a clip in the session view, then only 18 tests fail - otherwise 22 tests fail.

also, i am wondering about this
```
FAILED tests/test_application.py::test_application_get_version - assert (2 == 2 and 12 == 11)
```

is the test trying to see that my version 12 is not version11 and thus fails?

i'm wondering if the test clip stuff fails because the clip is not created first, or..? 

is there a specific ableton live project i should load before starting pytests?

@ideoforms
