### ISSUE TITLE
Strange behaviour with device parameters listeners.

### ISSUE THREAD

**Issue by betov75** [ideoforms/AbletonOSC#118]
First, thanks again for that amazing script. And for adding listeners for device parameters. Extremely useful.

I'm having a very strange bug. No matter what I do, all listeners are working, on any track, on any device or parameter. Except for track 2 (index 1). I receive values and value strings for all the other tracks, except the second one. Example, /live/device/start_listen/parameter/value',(1,0,x), x meaning 0 to 7, I don't receive any data. If I go to other groups of 8 parameters, some work, some don't. But only on track 2 (index 1). Track 1 or any other track after track 2, everything works flawlessly.

I've tried everything. Since I'm blind, I may be missing something, of course.

I only listen to groups of 8 parameters and stop listen to the previous ones before asking for new device parameters listeners.

I speak french so I hope it's clear enough.

Thanks!

**Comment by Daretreble** [comment]
I'm very sorry, my fault! :)

**Comment by betov75** [comment]
I'm closing the issue, the problem was on my side, sorry!

**Comment by ideoforms** [comment]
Thanks for the update! I did try to reproduce this but couldn't, so I'm glad you got to the bottom of it.
@Daretreble Was the underlying cause anything that other users could learn from?
