### ISSUE TITLE
sending out to port 8000 possible (for lemur)? (solved)

### ISSUE THREAD

**Issue by ericzang** [ideoforms/AbletonOSC#132]
I have just found AbletonOSC, looks great, thank you! Is it reasonably possible for me to configure AbletonOSC to send out to port 8000 (instead of 11001) so that lemur (which is set to only receive on 8000) can receive the osc messages? Or perhaps there is another approach? Thanks!

**Comment by ericzang** [comment]
I seem to have found it in constants.py, yes?

**Comment by ericzang** [comment]
somehow after a reboot and/or reconnects a test is working!

**Comment by esaruoho** [comment]
@ericzang hi, since this ticket has been solved, can you also close it?
