### ISSUE TITLE
How to bind to an external device ?

### ISSUE THREAD

**Issue by KBLiveSolutions** [ideoforms/AbletonOSC#14]
Hi

First of all, thanks for your script, it's awesome.

I'm trying to build an Arduino controller that would be based on this.
I'm wondering how to get the script working with an ip that would not be 127.0.0.1

Let's say my router attributes ip 192.168.1.12 to my controller, how can I let the script know where to send messages ?

I'm pretty n00b with ips and networking, so forgive my ignorance.

**Comment by ideoforms** [comment]
Hi @KBLiveSolutions, thanks for the comment. Previously, the script was hard-coded to always send replies to `127.0.0.1`. However, I've just addressed this issue, and replies will now be sent back to the IP address that the query came from (e.g. your controller). If you have a chance to take it for a spin, let me know how you get on!
