### ISSUE TITLE
Clips in arrangement view

### ISSUE THREAD

**Issue by MrRubberDucky99** [ideoforms/AbletonOSC#16]
Hi,
Great job so far reworking the LiveOSC. Woudl it be possible to be able to get clips that are on a track in arrangement view?
Thanks for all the great work so far!

Judah

**Comment by ideoforms** [comment]
Thanks for the kind comments. I've now added three endpoints for this, to query each track's Arrangement View clip names; lengths and start times (in beats):

```
/live/track/get/arrangement_clips/name
/live/track/get/arrangement_clips/length
/live/track/get/arrangement_clips/start_time
```

What are you seeking to do with Arrangement View clips?

**Comment by MrRubberDucky99** [comment]
I was planning on being able to launch/loop and generally control songs and set lists in arrangement view, and I wanted to be able to use clips to define loops etc.

(I know this would be easier in session view but I need to be able to run video)
