### ISSUE TITLE
live/song/get/cue_points Error

### ISSUE THREAD

**Issue by Coupe70** [ideoforms/AbletonOSC#25]
live/song/get/cue_points is checked off in my list, so I suppose it worked, but now it doesn't and gives me an error in the log.

(2022-11-29 00:25:33,451) [INFO] AbletonOSC: Error handling message: Traceback (most recent call last):
  File "C:\Users\Anja\Documents\Ableton\User Library\Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 110, in process
    assert isinstance(rv, tuple)
AssertionError

**Comment by ideoforms** [comment]
Good spot - fixed

**Comment by Coupe70** [comment]
Fix confirmed.
