### ISSUE TITLE
Installed basically works but doesnt send anything apart from /live/startup & /live/song/beat

### ISSUE THREAD

**Issue by designerfuzzi** [ideoforms/AbletonOSC#3]
In.

**Comment by designerfuzzi** [comment]
seems to be by design.. hmm, limited but all good so far.

what i don't understand is when it uses a sender port and a receiver port, why the do values names carry `/set` and `/get`.
Assuming this was meant to introduce some request design pattern.

**Comment by designerfuzzi** [comment]
100% sure sending a Int32 datatype, made print logs in my code everywhere to be super sure.
when testing my own OSC API `[_engine sendAddress:@"/live/track/get/volume" Int:0];` 
my log when building and sending the message looks like.. so i am sure i send `i` datatype.
 `got i, send i,` 

but i think i spotted some bug..
`AbletonOSC: Error handling message: Traceback (most recent call last):
  File "/Applications/AbletonLiveSuite64Bit/Ableton Live 11 Suite.app/Contents/App-Resources/MIDI Remote Scripts/AbletonOSC/abletonosc/osc_server.py", line 71, in process
    self.send(message.address, rv)
  File "/Applications/AbletonLiveSuite64Bit/Ableton Live 11 Suite.app/Contents/App-Resources/MIDI Remote Scripts/AbletonOSC/abletonosc/osc_server.py", line 47, in send
    for param in params:
TypeError: 'float' object is not iterable`

**Comment by designerfuzzi** [comment]
so changed test wise..
```python
# in /abletonosc/osc_server.py
def process(self) -> None:
        """
        Synchronously process all data queued on the OSC socket.
        """
        try:
            while True:
                data, addr = self._socket.recvfrom(65536)
                try:
                    message = OscMessage(data)

                    if message.address in self._callbacks:
                        callback = self._callbacks[message.address]
                        rv = callback(message.params)
                        
                        if rv is not None:
                            if rv is not tuple:
                                #self.logger.info("juijui: %s" % str(rv))
                                self.send(message.address, (rv,))
                            else:
                                self.send(message.address, rv)
                            
                    else:
                        self.logger.info("AbletonOSC: Unknown OSC address: %s" % message.address)
                except ParseError:
                    self.logger.info("AbletonOSC: OSC parse error: %s" % (traceback.format_exc()))
```

which as assumed results with some proper answer on my request.
<img width="299" alt="Bildschirmfoto 2021-11-29 um 02 31 13" src="https://user-images.githubusercontent.com/1221499/143795523-e695a21a-da96-4aae-b597-0497e0b297ae.png">

but now as told it answers with `"/get/"` which is kinda correct but still i would try to get rid of them its just wasting bandwidth..

**Comment by RickDDD** [comment]
Hey @designerfuzzi ,
first of all: There have been no developments and no answers on this project for 7 months.
So I'm afraid it has already been abandoned... 

I don't know if you are aware of this, but to get automatic status update sent, you have to start a
listener on the desired parameters. I remember that I tried one or two and was able get these
automatic updates. 
But there are only a few of these listeners implemented and also some (important) parameters
missing - I haven't looked into the Live API lately, but I'm pretty sure there must be more...

**Comment by designerfuzzi** [comment]
thanks for the reply..
But in general this means LiveOSC could work again with Live 11 when i do some tweaking..
LiveOSC suffers from the python2 switch a lot and i thought AbletonOSC looked more stable..
apart from the little problem i could solve today, it seems indeed a little less cumbersome to code for..

for the completeness i was going to compare it with the LiveOSC supported link list..

as more and more people will have the OSC challenge with Live11 your project is still kinda important.. 
dont forget that your work is never wasted..

**Comment by RickDDD** [comment]
I'm not the developer of this project!
I'm just a user and was happy when I found this port for Live 11 and a bit disappointed
when I realized it's far from complete and there is no ongoing development.
I understand a bit of what is listed in the Live API documentation, but not enough
of Python to work on the code. So if you are able and willing to improve and extend
this project, I'd be happy to assist and test.

**Comment by designerfuzzi** [comment]
My python knowledge is limited yet as well, but knowing C, C++, objc, swift it was not that hard to catch that little bug. 

I would not say it is far from complete as of what i see in code.. i would more think its not tested enough, which made it possible for this bug to exist, i guess. Well nothing comes from heaven unless we pick it up.

The Live API to me is more of a structure with a naming scheme and property register that someone published, also just existing because someone picked it up..

haha, thought you where the dev of this repo :-) 
I actually do this all here just because its a side project for the app partly shown in the pics.
Developed some kind a midi DAW that can hang in between ableton and hardware or in between Ableton and Logic or any kind of OSC device. Supports Push1&2, has midi filters, a independent Midi clock as well as MTC, and reads Elektron gear files from hardware and translates them to Ableton Sets with i dont know how much scenes are possible.. 
Pretty deep inside whats going on..

**Comment by designerfuzzi** [comment]
porting **LiveOSC** from python2 to python3 now. 
After a lot **import** rule changes it works now, Ableton accepts the script and finds its `_Framework` dependencies

next, porting LiveOSC/OSC.py to do properly MessageBuilding 
because 
python2 `unicode` **-> became** python3 `str`
python2 `str` **-> became** python3 `bytes`
And this is where i am a little stuck at the moment..

**Comment by Skateboss** [comment]
> porting **LiveOSC** from python2 to python3 now. After a lot **import** rule changes it works now, Ableton accepts the script and finds its `_Framework` dependencies
> 
> next, porting LiveOSC/OSC.py to do properly MessageBuilding because python2 `unicode` **-> became** python3 `str` python2 `str` **-> became** python3 `bytes` And this is where i am a little stuck at the moment..

Have you made any progress on porting LiveOSC? It would be amazing if you could get this working as I want to use Open Stage Control to dive a bit deeper than just sending MIDI messages to Abelton. 

Many thanks for your effort on this!

**Comment by designerfuzzi** [comment]
LiveOSC up and running.
But as i decided to modernise it a little as well i will post the result in a couple of days.

**Comment by RickDDD** [comment]
Amazing!
Let me know whenever you need something to be tested.

**Comment by Skateboss** [comment]
> LiveOSC for python3 up and running. Ended up changing the whole OSC unit to adapt the encode and decode mechanism of python3. While this simplified some code, other became more complex. Lessons learned, now i know why i love C.
> 
> But as i decided to modernise it a little as well i will post the result in a couple of days as a repo in my profile.

Thank you. I'm happy to test too. Many thanks!

**Comment by Skateboss** [comment]
@designerfuzzi Just wondreing if you've got an ETA for the update of LiveOSC please?
Sorry for asking but I desperatly want to test out my OSC control panel with Ableton.

Many thanks!

Kind regards,
Chris

**Comment by RickDDD** [comment]
> @designerfuzzi Just wondreing if you've got an ETA for the update of LiveOSC please? Sorry for asking but I desperatly want to test out my OSC control panel with Ableton.
> 
> Many thanks!
> 
> Kind regards, Chris

designerfuzzi is not the initial developer of LiveOSC / AbletonOSC, so I doubt there will something like
an update release or ETA. Maybe we are lucky and he will share his personal achievements though...

**Comment by Skateboss** [comment]
Ahh, Ok thank you.

Yes very excited for this
