### ISSUE TITLE
Log entries do not reflect origin of detected changes.

### ISSUE THREAD

**Issue by Coupe70** [ideoforms/AbletonOSC#30]
Log entries do not reflect origin of detected changes.

(2022-11-29 02:14:10,237) [INFO] Adding listener for track (0,), property: color
(2022-11-29 02:14:10,239) [INFO] Adding listener for track (1,), property: color
(2022-11-29 02:14:10,240) [INFO] Adding listener for track (2,), property: color
(2022-11-29 02:14:10,243) [INFO] Adding listener for track (0,), property: name
(2022-11-29 02:14:10,244) [INFO] Adding listener for track (1,), property: name
(2022-11-29 02:14:10,245) [INFO] Adding listener for track (2,), property: name
(2022-11-29 02:14:14,537) [INFO] **Property color changed: 8912743**
(2022-11-29 02:14:26,101) [INFO] **Property name changed: 2-Audio**
(2022-11-29 02:14:40,191) [INFO] **Property name changed: 3-Audio**

**Comment by ideoforms** [comment]
Fixed

**Comment by Coupe70** [comment]
Fix confirmed.
