### ISSUE TITLE
Tolerate floats?

### ISSUE THREAD

**Issue by ideoforms** [ideoforms/AbletonOSC#33]
Request from lengwenings: Could AbletonOSC tolerate floats as IDs?

```
TouchOSC scripting has two ways of sending OSC messages - simple and complex.
Simple would be enough for AbletonOSC, but when using the simple way TouchOSC 
auto-converts all numbers to floats which AbletonOSC does not tolerate.

This means you have to script every OSC message complex:

sendOSC( {'/live/set/clip/name', { {tag = 'i', value = 0 },  {tag = 'i', value = 2 } ,  {tag = 's', value = "test" } } } )

instead of simple:

sendOSC( '/live/set/clip/name', 0, 2, "test" )
```

**Comment by ideoforms** [comment]
Done

**Comment by Coupe70** [comment]
Change confirmed - floats and simple scripting work now, calling with ints is still functional.
Thank you!

Just to avoid confusion if others try to copy the above scripting line:
It's **NOT** /live/set/clip/name like I wrote twice in my request, it's **/live/clip/set/name**
Maybe you can edit this above.

**Comment by Coupe70** [comment]
@ideoforms 

`/live/device/get/parameter/value` does not tolerate floats and returns **Error handling OSC message: Invalid index type**
When I use the complex OSC command to send integers it works as expected.

Doublechecked with `/live/device/get/name` and this tolerates floats.

Only obvious difference I can see is that `get/name` needs 2 arguments and `get/parameter/value` needs 3.

**Comment by zbynekdrlik** [comment]
Same issue here with "invalid index type" for /live/device/get/parameter/value

**Comment by Coupe70** [comment]
@ideoforms 

Seems that `/live/song/get/track_data` does not tolerate floats, 
`/live/song/get/track_data 0 12 track.name`
returns **'float' object cannot be interpreted as an integer**

**Comment by Coupe70** [comment]
@ideoforms 

> have you looked at using [/live/song/get/track_data](https://github.com/ideoforms/AbletonOSC?tab=readme-ov-file#querying-trackclip-data-in-bulk-with-livesonggettrack_data) for batch property queries?

Yes, I did (see above) ;-)

**Comment by Coupe70** [comment]
I tried to query track.name and clip.name with the more complex way to send OSC in TouchOSC and it works.
All I have to do to parse it is to query `/live/song/get/num_scenes`, otherwise I can't tell when the clip names
of one track end and a new track begins.
I miss the opportunity to get clip_slot.has_stop_button.
No problem to query it individually, but it's kind of missing to get all important information with `/get/track_data`.

**Comment by ideoforms** [comment]
I've added support for `has_stop_button` to complete the picture :)
track_data and device parameters should also now tolerate float input.

**Comment by Coupe70** [comment]
@ideoforms 
Floats work, has_stop_button works, but it is `clip.has_stop_button` where it should be `clip_slot.has_stop_button`.

**Comment by ideoforms** [comment]
Ah yes, have rewritten to `clip_slot.has_stop_button`

**Comment by Coupe70** [comment]
Perfect.
