### ISSUE TITLE
Return errors via OSC?

### ISSUE THREAD

**Issue by Coupe70** [ideoforms/AbletonOSC#39]
Should some errors and infos that go to the log maybe also be returned via OSC
in some way, maybe as /AbletonOSC/error (string) or something? Not to be handled
by TouchOSC in any way, just to provide a realtime feedback in the OSC monitor when 
something is wrong.
Wouldn't do any harm when everything is ok as it wouldn't cause any additional messages, 
but would make it easier to try and explore AbletonOSC and to develop and debug tools using 
AbletonOSC as it would be easier to understand why nothing happens in some situations.

Some examples how that came to my mind:
**AttributeError: 'NoneType' object has no attribute 'color'** - when you try to get color from an empty clip slot.
**AttributeError: 'NoneType' object has no attribute 'gain'** - when you try to get gain from an empty clip slot.
**RuntimeError: Gain is only available for Audio Clips** - when you try to get gain from a midi clip.
etc.

And for any kind of typos or calls that are not available:
**[INFO] AbletonOSC: Unknown OSC address: /live/track/get/clips/colr 
[INFO] AbletonOSC: Unknown OSC address: /live/track/get/clips/color_index**

**Comment by ideoforms** [comment]
Nice idea. Done! Errors are now sent to /live/error.

**Comment by Coupe70** [comment]
Works. 👍
