### ISSUE TITLE
Getter for time signature

### ISSUE THREAD

**Issue by rienheuver** [ideoforms/AbletonOSC#43]
I'm working on something where I would like to keep count of the measures. However, there seems to be no listener for that, so I figured I'd build my own basing it off of `/live/song/beat`. The thing is, I don't know the time signature of the song and can't just assume it is 4/4. I found the song properties `signature_denominator` and `signature_numerator` here: https://docs.cycling74.com/max8/vignettes/live_object_model#Song.
However, I can't get them (yet), can I? I tried listening for them with `/live/song/start_listen/signature_denominator` but I get an "Unknown OSC address" error. I also tried `get` instead of `start_listen`, but had the same result.

Am I overlooking something here?

**Comment by ideoforms** [comment]
Thanks, good spot, these had not yet been exposed. I've just added getters for `signature_denominator` and `signature_numerator`, and verified that listeners are also now working for them.

Would love to hear more about what you're developing! If you're happy to share any info, please send me a note - https://erase.net/contact/
