### ISSUE TITLE
Handling of all active listeners

### ISSUE THREAD

**Issue by Coupe70** [ideoforms/AbletonOSC#45]
It's sometimes hard to keep an overview of all started listeners and it gets more difficult with the new wildcard *.

Would it be possible to get something like `/live/get/allactivelisteners` and `/live/stop/allactivelisteners` ?
Probably this is only for development purposes and may be too much work to implement as listeners "belong" to different .py files, right?

**Comment by ideoforms** [comment]
Yeah, I think this would be a fairly heavy lift and only possible with a fair bit of added code to track listener creation/destruction on the AbletonOSC side (as the Ableton API itself has no way to query this). Closing unless a very strong reason arises to do this.
