### ISSUE TITLE
Track type

### ISSUE THREAD

**Issue by Coupe70** [ideoforms/AbletonOSC#48]
Is there a way to find out if a track is midi / audio (/ send / master) ?
Couldn't find anything in AbletonOSC, but neither in the Live API - seems there is no 'track type'
property. Strange as it seems to be of interest to know which calls you can make to a certain track.
All I could find was "has midi input/output" and "has audio input/output" which will help to conclude 
the desired information, but doesn't seem very elegant...

**Comment by ideoforms** [comment]
Yes, this is a strange one. I looked it up and it just doesn't seem to be a thing. The [docs](https://structure-void.com/PythonLiveAPI_documentation/Live11.0.xml) make quite a strong implication that `has_midi_input` and `has_audio_input` are the intended ways of querying the track "type", as there is a comment in each:

```
has_midi_input Property - This is true for all MIDI Tracks.
has_audio_input Property - This is true for all Audio Tracks.
```

So I guess this is working as expected, and `has_midi_input` / `has_audio_input` should be seen as synonymous with `is_midi_track` / `is_audio_track` respectively.
