### ISSUE TITLE
Request: 3 new clip listeners

### ISSUE THREAD

**Issue by Coupe70** [ideoforms/AbletonOSC#49]
I would like to have the following 3 clip listeners that are quite essential
to build a TouchOSC template for session view:

/live/clip/start_listen/color
/live/clip/start_listen/name
/live/clip/start_listen/length

Edit: Make it 5 ;-)

/live/clip_slot/start_listen/has_clip
/live/clip_slot/start_listen/has_stop_button

**Comment by ideoforms** [comment]
I've just double-checked and all of these are already implemented, just not documented in the README.
One thing to bear in mind is that calling `start_listen` for (e.g.) `name` or `color` on a clip_slot that is not populated does not work — because there is no clip in the clip_slot for Live to listen to. So if you wanted to keep a client updated with the correct colour of the slot contained in a clip, you would need to start listening for the presence of a clip in the slot, and _then_ start listening to changes in that clip... which I appreciate may get a bit complicated...

**Comment by Coupe70** [comment]
@ideoforms 

`/live/clip/start_listen/color` 
`/live/clip/start_listen/name` 
`/live/clip_slot/start_listen/has_clip`
`/live/clip_slot/start_listen/has_stop_button`

work, but do not return track & clip ID while the manual `get` calls do.

`/live/clip/start_listen/length` returns **Error handling OSC message: 'Clip' object has no attribute 'add_length_listener'**

**Comment by Coupe70** [comment]
@ideoforms 

Hi!
Tried again after being absent for a long time.

`/live/clip/start_listen/color`
`/live/clip/start_listen/name`

work as expected now, returning track & clip ID and the value.

`/live/clip_slot/start_listen/has_clip`
`/live/clip_slot/start_listen/has_stop_button`

return **/live/error STRING(Error handling OSC message: 'tuple' object has no attribute 'add_has_clip_listener')**
and **/live/error STRING(Error handling OSC message: 'tuple' object has no attribute 'add_has_stop_button_listener')**
I THINK they had been working before, just not returning track & clip ID.
The corresponding `get` requests work on the same clip slot.

`/live/clip/start_listen/length`

still returns **/live/error STRING(Error handling OSC message: 'Clip' object has no attribute 'add_length_listener')**

**Comment by tonymckendry** [comment]
Bump - I ran into the behavior described above today when attempting to add a `has_clip` listener onto a given slot. Thought maybe I was doing something wrong, but then I found this post.

**Comment by ideoforms** [comment]
Finally fixed. Thanks @Coupe70, I think they were actually working before but this was broken in a regression 😬 Have added a test to prevent this happening again...

**Comment by Coupe70** [comment]
@ideoforms 
Great! I'll try it out...NEXT YEAR. 😄

**Comment by Coupe70** [comment]
@ideoforms 
`/live/clip_slot/start_listen/has_clip` and
`/live/clip_slot/start_listen/has_stop_button`
do work now!

But 
`/live/clip/start_listen/length`
still returns **/live/error STRING(Error handling OSC message: 'Clip' object has no attribute 'add_length_listener')**
while `/live/clip/get/length` keeps working as expected.
