### ISSUE TITLE
Weird Null Error

### ISSUE THREAD

**Issue by script-head** [ideoforms/AbletonOSC#52]
I made a thing in touchdesigner to either speed up or slow down tracks across multiple BPMs to ensure the show is in sync if I change a song's bpm, however whenever I send the bpm value to AbletonOSC (at /live/song/set/tempo) I get this error message:

```
(2023-01-20 21:47:23,734) [INFO] Setting property for song: tempo (new value 90.0)
(2023-01-20 21:47:23,734) [ERROR] AbletonOSC: Error handling OSC message: Python argument types in
    None.None(Song, str)
did not match C++ signature:
    None(class TPyHandle<class ASong>, float)
(2023-01-20 21:47:23,735) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\scripthead\Documents\Ableton\User Library\Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 108, in process
    rv = callback(message.params)
  File "C:\Users\scripthead\Documents\Ableton\User Library\Remote Scripts\AbletonOSC\abletonosc\handler.py", line 32, in _set_property
    setattr(target, prop, params[0])
Boost.Python.ArgumentError: Python argument types in
    None.None(Song, str)
did not match C++ signature:
    None(class TPyHandle<class ASong>, float)
```

I was running Ableton 11.2.6

**Comment by ideoforms** [comment]
This error indicates that the `90.0` argument has been passed as a string type, rather than as a float. I'm not familiar with TouchDesigner, but you'll need to cast the `90.0` output argument to a float type for it to be received correctly by AbletonOSC. That should hopefully solve the issue.

**Comment by script-head** [comment]
Ah, I forgot Touch Designer is weird with some things, I casted the variable as a float and now everything works better than I expected, thank you so much this library is a god send.
