### ISSUE TITLE
Request: Get audio output value (complementary to getting the volume set in ableton)

### ISSUE THREAD

**Issue by CoponatRecords** [ideoforms/AbletonOSC#54]
I am writing a Python tool that does automatic camera switching for a live set, it requires to be able to read the audio inputs in specific tracks to know what instruments are being played.

I linked my script to ableton with python-osc and abletonosc, but then discovered get/volume returns the value of the volume set in ableton, not the value of the audio

**Comment by CoponatRecords** [comment]
If anyone is looking for a workaround, you can use an envelope follower mapped to a utility's gain and then use the /live/device/get/parameters/value to get a value for the audio level.

**Comment by ideoforms** [comment]
Nice workaround!
I've also now added support for the Track property `output_meter_level`, which should do what you're looking for.

**Comment by CoponatRecords** [comment]
Thanks for the update !

**Comment by CoponatRecords** [comment]
It seems i can get most track attibutes: volume, color, panning ... working, but not some others like  output_meter_level, can_be_armed ...  any idea what might be going on ?
