### ISSUE TITLE
Seemingly missing playback functionality

### ISSUE THREAD

**Issue by DeveeiveD** [ideoforms/AbletonOSC#56]
So afaik for playback control there are functions:
* play
* stop
* continue
* set current time 

However if you invoke play, pause and set current time somewhere else, you are then unable to continue/start at that position for the following playback.

**Comment by ideoforms** [comment]
I don't totally follow... Can you give an example of the sequence of interactions that demonstrate the problematic behaviour?

**Comment by ideoforms** [comment]
Closing as not enough information to reproduce.
