### ISSUE TITLE
/live/clip/add/notes doesn't seem to work

### ISSUE THREAD

**Issue by jasonlevine** [ideoforms/AbletonOSC#59]
Hello, 

I am able to create and rename clips, but I can't add midi notes to them.
I am sending the following params to the "/live/clip/add/notes" address: `[0, 0, 60, 0, 4, 127, 'on']`
I know that the track_id and clip_id are correct because the clip was created using liveosc and I can see the clip in Live.
Have I made a mistake with the parameters?  Or can anyone confirm that they have had success in using LiveOSC to add midi notes to a clip?

Any help is appreciated,
Thank you for this awesome project!

**Comment by steve-meyer** [comment]
I am able to add notes. I have had to make sure that I send the correct data types, which are the following types:

* MIDI note: integer
* clip position: double
* duration: double
* velocity: float
* inactive: boolean

I am working in a JavaScript client, so probably an uncommon way, but maybe your array should be:

`[0, 0, 60, 0.0, 4.0, 127.0, false]`

**Comment by jasonlevine** [comment]
Thanks for the reply, Steve.  I tried the array you shared but it didn't work.  Can you tell me a bit about the state of your Ableton project?  Is the clip selected? are you in a particular view?  I know these things shouldn't matter, I just want to try to reproduce your success.

**Comment by jasonlevine** [comment]
Ok got it working from Python with this array:  `[0, 0, 60, 0, 4, 127, False]`

The decimal points don't seem to matter. What is important is to send a boolean for muted and not "on/off" as it states in the readme.  @ideoforms Maybe the Readme could be updated to reflect that a boolean is required here?

Thank you :)
