### ISSUE TITLE
Cue Points

### ISSUE THREAD

**Issue by burkholderm** [ideoforms/AbletonOSC#6]
Can you add a way to get cue point names, and move between them? Such as next, previous and a specific cue point?

**Comment by ideoforms** [comment]
I have now added support for querying and triggering cue points:
```
/live/song/get/cue_points
/live/song/cue_point/jump
```

One thing to note is that the list of cue points are returned in the same order as in the LOM API, which doesn't seem to be sequentially in time but in the order they were added. I am trying to be as faithful as possible to the LOM, so will preserve this behaviour.
