### ISSUE TITLE
Feature request: Export Audio

### ISSUE THREAD

**Issue by jasonlevine** [ideoforms/AbletonOSC#62]
Hello,

I'm not sure if this is possible, but it would be amazing if exporting audio could be automated with this library.

Something like this:
```
export_settings = {
    "file_path": "/path/to/exported/audio.wav",
    "num_channels": 2,
    "sample_rate": 44100,
    "bit_depth": 24,
    "type": "wav",
    "start_time": 0.0,
    "end_time": 10.0,
    "render_stems": False,
    "create_analysis_file": False
}

client.send_message("/live/export", [export_settings])
```

**Comment by ideoforms** [comment]
That would be excellent, but I can't see any sign of this in the Live Object Model API docs, and this tumbleweed thread suggests it's not possible in M4L:
https://cycling74.com/forums/exporting-ableton-live-audio-with-m4l

As a general rule, if something is not possible in M4L, it is likely not exposed by the Ableton API. :-(
I'll therefore close this issue, but perhaps Ableton will expose this at some point in the future...
