### ISSUE TITLE
script not loading - syntax error

### ISSUE THREAD

**Issue by CrossmodGlennVS** [ideoforms/AbletonOSC#63]
I get a syntax error on :
local_addr: Tuple[str, int] = ('0.0.0.0', OSC_LISTEN_PORT)

I'm running Live 9, is that the problem?

**Comment by ideoforms** [comment]
Yes, AbletonOSC only supports Live 11. Earlier versions of Live use Python 2 for their Remote Scripts, which has a different syntax. You might want to look at [LiveOSC](https://github.com/ideoforms/LiveOSC), although this is no longer maintained (and has a different set of OSC endpoints, supported features, etc).
