### ISSUE TITLE
/live/clip_slot/start_listen/has_clip doesn't return all expected params

### ISSUE THREAD

**Issue by uholland** [ideoforms/AbletonOSC#65]
Current behaviour:
It returns only true/false on clip creation and clip removal. Index of track and scene is missing in the returning params on /live/clip_slot/get/has_clip. 

(Querying /live/clip_slot/get/has_clip directly returns all 3 params as expected.)

Expected behaviour:
Return all 3 params track index, scene index and a boolean if a clip exists

**Comment by ideoforms** [comment]
Thanks for the report, this is now fixed.
