### ISSUE TITLE
Clip postion - has anyone been able to use it?

### ISSUE THREAD

**Issue by samplenopeso** [ideoforms/AbletonOSC#67]
I see that in the clip.py file in the part referring to the clip_position listeners we have:

 ` # TODO: tidy up and generalize this`

I've already tried the instructions in the readme. I found the use of the /live/clip/get/playing_position and /live/clip/start_listen/playing_position messages a bit confusing.

At some point it seems that /live/clip/start_listen/playing_position sends the parameters to /live/clip/get/playing_position... Anyway, I don't understand.

I tried with both messages and it didn't work.

I also found a closed topic where there are a few more comments about it, but soon he entered another subject out of context (so I ask everyone's permission to reopen this new topic)

Has anyone been able to use it?

Thanks!

**Comment by StrongBearCeo** [comment]
This doesn't work for me, either. Whenever I tried to start / stop listening to clip playing position, I got this error

`[WARNING] AbletonOSC: Traceback (most recent call last):
  File "/abletonosc/osc_server.py", line 109, in process
    rv = callback(message.params)
  File "/abletonosc/clip.py", line 57, in clip_callback
    rv = func(clip, *args, params[0:])
  File "/abletonosc/clip.py", line 149, in clip_remove_playing_position_listener
    track_index, clip_index = track_clip_index
TypeError: cannot unpack non-iterable Clip object`

**Comment by ideoforms** [comment]
Now fixed.

**Comment by paulmacmillan** [comment]
Hey, seems like I have a similar issue.
The playing position listener doesn't register but the getter for the same info is working.

Here are screenshots with error message and normal state for debug if needed.
<img width="643" alt="Screenshot 2024-05-11 at 00 09 58" src="https://github.com/ideoforms/AbletonOSC/assets/38572718/ed7f59cb-7a7d-45e4-b004-7db99524fa6b">
<img width="641" alt="Screenshot 2024-05-11 at 00 12 48" src="https://github.com/ideoforms/AbletonOSC/assets/38572718/6485f4db-bd98-4320-b323-90e2b3ad537b">

Thanks for your help @ideoforms
