### ISSUE TITLE
output_meter_level  choppy due possible beat send - TouchOSC

### ISSUE THREAD

**Issue by zbynekdrlik** [ideoforms/AbletonOSC#69]
Hi, when I register output_meter_level for exact track, sending data are choppy. Interruption of receiving data are somehow possible connected with receiving 
/live/song/beat) INT32(41819)

**Comment by ideoforms** [comment]
This is likely an inherent limitation as Live only sends data on a 100ms interval (10ms), so can't be fixed unfortunately.  This could also be exacerbated by Wi-Fi jitter. Closing.
