### ISSUE TITLE
/live/clip/notes/get, remove and similar...

### ISSUE THREAD

**Issue by fferri** [ideoforms/AbletonOSC#7]
It would be nice to have methods for listing and removing notes in a clip, so it is possible to get a complete reconstruction of the liveset state.

**Comment by ideoforms** [comment]
Totally agree, this will be included in the API for sure.

**Comment by ideoforms** [comment]
Now supported:
```
/live/clip/get/notes
/live/clip/add/notes
/live/clip/remove/notes
```

Docs: [Clip API](https://github.com/ideoforms/AbletonOSC#clip-api)
