### ISSUE TITLE
AbletonOSC only works on Mac OS X because of run-console.py

### ISSUE THREAD

**Issue by EricBuist** [ideoforms/AbletonOSC#71]
Hi, the test utility run-console.py fails to start, cannot find readline module which is not available for Windows. The documentation gives no other clue on how to make use of AbletonOSC after it is installed into Live 11 and enabled as a control surface. Is this package working on Windows or just on Mac OS X?

**Comment by markmarijnissen** [comment]
`pip install pyreadline3` solves the issue, see https://stackoverflow.com/questions/51157443/pythons-readline-module-not-available-for-windows

**Comment by ideoforms** [comment]
Thanks, I've added a warning when `run-console` is run on a Windows machine, with instructions on installing pyreadline3.
