### ISSUE TITLE
Add notes doesn't work on run_console

### ISSUE THREAD

**Issue by ggyshay** [ideoforms/AbletonOSC#78]
I have tried `/live/clip/add/notes 0 0 69 0.0 0.25 100 False` and any other permutation of parameters, with parenthesis over the notes, with brackets over the notes, with different types for muted (false, False, 0, "False", "false"). no response and no notes are created.
I've tried to check the logs, they are not being created by simply running run_console, so I tried running client.py directly, it still doesn't create the log folder, I tried creating the log folder myself, didn't work either.
Running manager by itself depends on an `ableton` package, I tried installing pylive but its not it.

Macbook pro M1 Ventura 13.1
Ableton Live 11.2.11

**Comment by ideoforms** [comment]
Hmm, if the `logs` folder isn't created, it's probably the case that AbletonOSC isn't set up and opening correctly. Can you confirm whether it appears and is selected as a Control Surface in Preferences > Link/Tempo/MIDI?

I have just tested here, `/live/clip/add/notes 0 0 69 0.0 0.25 100 0` should work fine in the console. You're right that False is not parsed correctly though... I will have to add some smarter behaviour to the console to handle this.

**Comment by ggyshay** [comment]
It does show up in Link Tempo MIDI, I had other devices setup, I dumped them and still nothing. When I choose AbletonOSC it does display the Listening on port ... message. One thing Im thinking about is my ableton folder is inside documents, not in music like the documentation for remote scripts suggests but I imagine this path is not relevant, also im using a Mac with m1, not in rosetta

**Comment by pejrich** [comment]
I found this quite confusing too, since the docs state `velocity is MIDI velocity index, mute is true/false` I was passing in `... 100 False`, but the error reads:

```
MidiNoteSpecification.__init__(MidiNoteSpecification)
did not match C++ signature:
__init__(_object*, int pitch, double start_time, double duration, float velocity=100.0, bool mute=False, float probability=1.0, float velocity_deviation=0.0, float release_velocity=64.0)
```

Which led me to believe my velocity should be 100.0, but rather the issue was that it needed to 0/1 rather than true/false(or True/False).

**Comment by ggyshay** [comment]
When I tail Ableton logs I get info: Python: INFO:abletonosc:999 - AbletonOSC: Unknown OSC address: /live/clip/add/notes

**Comment by ggyshay** [comment]
I've just found out that I had an older version of abletonOSC (?) in my ableton remote scripts inside the ableton content, that was causing the problem, all solved now!
