### ISSUE TITLE
Is there a Python API (like pylive)?

### ISSUE THREAD

**Issue by fferri** [ideoforms/AbletonOSC#8]

**Comment by fferri** [comment]
Cool. I am making some experiments with this, and I have also a few ideas for projects based on this.
Btw do you plan to release this under some opensource license?

**Comment by ideoforms** [comment]
Just added a LICENSE.md that puts this under the terms of the MIT license, so free for commercial and non-commercial use.

**Comment by ideoforms** [comment]
Just added a LICENSE.md that puts this under the terms of the MIT license, so free for commercial and non-commercial use.
