### ISSUE TITLE
Suggestion regarding module structure

### ISSUE THREAD

**Issue by dgrigonis** [ideoforms/AbletonOSC#83]
This repo can potentially be used as a Python package as it has a lot of unique tools that can not be found elsewhere and most importantly AbletonOSCClient.

however, it has quite an inconvenient folder structure for it. If it is placed in site-packages, then an entry point to it is `from client import AbletonOSCClient`, which makes it ambiguous and furthermore runs a risk of name conflicts due to very generic package name at the top level.

My suggestion would be:
```
AbletonOSC/
    abletonosc/
        osc/
        abletonosc/
        client/
        __init__.py  (with create instance thing)
        manager.py
        run_console.py
    tests/
    <md files>
```

This way, the AbletonOSC folder can simply be added as a dev package, via the *.pth file given structure decently complies with one of the packages. Then the usage is very convenient:
```python
from abletonosc.client import AbletonOSCClient
```
And to run console:
```bash
python -m abletonosc.run_console
# or create __main__.py, then:
python -m abletonosc
```

One slight inconvenience is that the lowercase `abletonosc` folder would be the one copied to **Remote Scripts** folder and it would show up as a lowercase name in Ableton itself, which is out of style there, complying with Python or with Ableton would be the decision to make given you consider my suggestion.

Love your work!

**Comment by ideoforms** [comment]
Thanks @dgrigonis. It is indeed a rather odd and un-idiomatic folder structure.... but the rationale is to make it as simple as possible for people to install when downloading from GitHub by unzipping into their `Remote Scripts` folder. For this to work, there needs to be a `manager.py` (and `__init__.py`) at the top-level, which then import the other modules from their respective directories.

At some point in future, I might make a cleaner installer, possibly using the same kind of one-liner that [Homebrew uses](https://brew.sh/)...

As a separate issue, I think what you are getting at is the desire to import and use the client element of AbletonOSC to control the Live session from Python. For this, I recommend [pylive](https://github.com/ideoforms/pylive), which is the client-side counterpart and has Pythonic abstractions that makes it simple to interface with.

**Comment by dgrigonis** [comment]
Thanks for this!

So in what cases is your package better than pylive? Isn't your package interfacing with live as well? What are the differences?

Apart from the obvious - OSC messages vs RPC, which is probably just abstracted OSC or similar.

**Comment by ideoforms** [comment]
@dgrigonis Yes exactly, I created pylive as the client-side counterpart. AbletonOSC runs inside Live, listens for OSC connections and provides information about the set state, listens for triggers, etc; pylive runs in your Python program, and does the work of crafting all of the OSC messages to trigger and query AbletonOSC. The advantage of using pylive is that you don't need to hand-create OSC messages (or even be aware of OSC) to interact with the set, plus it handles things like querying/caching set state.

The drawback is that pylive doesn't yet cover the whole set of properties/methods provided by AbletonOSC as I haven't had the time to expand it that far. Any contributions welcomed. Thanks!
