### ISSUE TITLE
Is ableton.v2 API documented somewhere?

### ISSUE THREAD

**Issue by fferri** [ideoforms/AbletonOSC#9]

**Comment by fferri** [comment]
Or any plan to do so?

E.g.: adding typing annotations, comments in code, explaining the base concepts (what is a layer?)

**Comment by ideoforms** [comment]
I recommend taking a look at the [Live API version 11.0.0](https://structure-void.com/PythonLiveAPI_documentation/Live11.0.xml) docs, reverse-engineered by Julien Bayle.
