### ISSUE TITLE
How to better debug server code?

### ISSUE THREAD

**Issue by StrongBearCeo** [ideoforms/AbletonOSC#91]
Typically, how can I tell if there's a syntax error in the server-side code, such as in osc_server.py? It doesn't provide any information in the abletonosc.log; it remains silent.

Whenever I make changes to the server code, I have to restart Ableton Live. Is there a more efficient alternative?

**Comment by d1One** [comment]
I am not 100% sure but I think you can just reload your Ableton project from File>Open Recent, it should refresh it.

**Comment by ideoforms** [comment]
Good question. Unfortunately, for something to show up in `abletonosc.log`, the script has to successfully be parsed and run. Any compile-time issues end up in a separate Live internal log file, in the `Live Reports/Usage` directory. 

Information on this is in [CONTRIBUTING.md](https://github.com/ideoforms/AbletonOSC/blob/master/CONTRIBUTING.md).

Unfortunately, the error gets collapsed into a single line (example below) so it takes a bit of effort to look through, but it should be enough for debugging.

<img width="1367" alt="image" src="https://github.com/ideoforms/AbletonOSC/assets/302318/13a3bfbd-820b-4390-aeb6-2e6d356565ee">
