### ISSUE TITLE
Removing listeners?

### ISSUE THREAD

**Issue by Singer5870** [ideoforms/AbletonOSC#93]
Hi,
does someone know how to remove listeners, or under which circumstances they are removed automatically? I have a 16-channel virtual controller that 'moves' through the Ableton session and creates new listeners every time it changes the tracks it focuses on. Is there a way to disable listeners again so AbletonOSC stops sending me information about tracks I'm not accessing anymore?

**Comment by everydaymilk** [comment]
I found out this is already implemented by replacing '/start_listen' with '/stop_listen'.

**Comment by ideoforms** [comment]
Spot on, any `start_listen` can be removed later with the corresponding `stop_listen`.
