### ISSUE TITLE
seemingly missing a way of starting the recording of audio clip (midi clip does work, but need audio clip recording on/off toggle)

### ISSUE THREAD

**Issue by esaruoho** [ideoforms/AbletonOSC#94]
hi, i'm trying to wrap my mind around this repository. my usecase is this: i have 15 audiotracks which are all armed, and i'd prefer to send them "record audio to this slot" messages in the session view.

i _thought_ it would be `/live/clip/fire` but apparently not. Is there a way of starting the creation of a clip

then i tried if it might be `/live/clip_slot/create_clip` but that only works for midiclips.

i'd love to be able to start/stop the recording of one specific audiotrack. what's the process?

**Comment by ideoforms** [comment]
Hi @esaruoho, you were very close — there is also a `/live/clip_slot/fire` method. It's similar to `/live/clip/fire` but operates on an empty `clip_slot`, so can be used for recording.

You can then call `/live/track/stop_all_clips` to stop the recording (or `/live/clip/fire` to start playing the recorded clip).

Hope that helps!

**Comment by esaruoho** [comment]
hi @ideoforms , `/live/clip_slot/fire` is missing from the readme.md. i don't know how to find out which other functions are missing, or how to find the missing functions out.

**Comment by RibbleFripFnibbulator** [comment]
Ran into this same issue, was wondering why clip/fire wasn't starting any recordings or group tracks! Switching to clip_slot resolved both issues. Thanks guys!
